version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d
    depends_on:
      - mueblesstgo-app

  postgres-db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=MueblesStgo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lmao2
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  mueblesstgo-app:
    image: grillitoxc/mueblesstgo:latest
    container_name: app
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/MueblesStgo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lmao2
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure